># E-Commerce Sales Performance Dashboard

># preprocessing

> ## Import librairies

In [2]:
import pandas as pd

> ## Read Dataset

In [3]:
df = pd.read_csv(r"C:\Users\LOL\Desktop\Projects\Project visual\data\Sample - Superstore.csv", encoding='latin1')

> ## Exploratory data

In [4]:
df.shape
print(f"Num of row:{df.shape[0]}\nNum of column:{df.shape[1]}")

Num of row:9994
Num of column:21

In [5]:
print(f"column name: {df.columns.tolist()}")

column name: ['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

In [6]:
df.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [8]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [9]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [10]:
df.columns=df.columns.str.strip().str.lower().str.replace(" ","_").str.replace("-","_")
print(f"clean column: {df.columns.to_list()}")

clean column: ['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id', 'customer_name', 'segment', 'country', 'city', 'state', 'postal_code', 'region', 'product_id', 'category', 'sub_category', 'product_name', 'sales', 'quantity', 'discount', 'profit']

In [11]:
df.dtypes

row_id             int64
order_id          object
order_date        object
ship_date         object
ship_mode         object
customer_id       object
customer_name     object
segment           object
country           object
city              object
state             object
postal_code        int64
region            object
product_id        object
category          object
sub_category      object
product_name      object
sales            float64
quantity           int64
discount         float64
profit           float64
dtype: object

In [12]:
df["order_date"]=pd.to_datetime(df["order_date"])
df["ship_date"]=pd.to_datetime(df["ship_date"])
df["month"]=df["order_date"].dt.month
df["year"]=df["order_date"].dt.year
df["day"]=df["order_date"].dt.day
df["month_name"]=df["order_date"].dt.month_name()
df["day_name"]=df["order_date"].dt.day_name()
df["year_month"] = df["order_date"].dt.to_period("M").astype(str)

In [13]:
df.dtypes

row_id                    int64
order_id                 object
order_date       datetime64[ns]
ship_date        datetime64[ns]
ship_mode                object
customer_id              object
customer_name            object
segment                  object
country                  object
city                     object
state                    object
postal_code               int64
region                   object
product_id               object
category                 object
sub_category             object
product_name             object
sales                   float64
quantity                  int64
discount                float64
profit                  float64
month                     int32
year                      int32
day                       int32
month_name               object
day_name                 object
year_month               object
dtype: object

In [14]:
df["profit_margin"] = df["profit"] / df["sales"]

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.head(3)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,quantity,discount,profit,month,year,day,month_name,day_name,year_month,profit_margin
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,2,0.0,41.9136,11,2016,8,November,Tuesday,2016-11,0.16
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,3,0.0,219.5820,11,2016,8,November,Tuesday,2016-11,0.30
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,2,0.0,6.8714,6,2016,12,June,Sunday,2016-06,0.47

In [17]:
df.to_csv("cleaned_dataset.csv",index=False)
df_clean=pd.read_csv("cleaned_dataset.csv")
df_clean.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,quantity,discount,profit,month,year,day,month_name,day_name,year_month,profit_margin
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,2,0.00,41.9136,11,2016,8,November,Tuesday,2016-11,0.1600
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,3,0.00,219.5820,11,2016,8,November,Tuesday,2016-11,0.3000
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,2,0.00,6.8714,6,2016,12,June,Sunday,2016-06,0.4700
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,5,0.45,-383.0310,10,2015,11,October,Sunday,2015-10,-0.4000
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,2,0.20,2.5164,10,2015,11,October,Sunday,2015-10,0.1125

> # Visualization

> # import Visual Lib

In [18]:
import plotly.express as px

In [19]:
df["category"].unique()

array(['Furniture', 'Office Supplies', 'Technology'], dtype=object)

> ### Comparison Charts (Column Chart ,Bar Chart,Stacked Column Chart, Stacked Bar Chart, Clustered Column Chart, and Clustered Bar Chart)

> # 1) Column Chart —Total Sales by Category
>> ## Which region generates the highest total profit?

In [34]:
sales_by_category = df.groupby("category")["sales"].sum().reset_index()
sales_by_category = sales_by_category.sort_values("sales", ascending=False).reset_index(drop=True)

sales_by_category["type"] = "Standard"
sales_by_category.loc[0, "type"] = "Max"

fig_column = px.bar(
    sales_by_category,
    x="category",
    y="sales",
    title="Total Sales by Category",
    text=sales_by_category["sales"]/1000,
    color="type",
)

fig_column.update_traces(
    texttemplate="%{text:.0f}K",
    textposition="outside"
)

color_map = {
    "Max": "#1E88E5",
    "Standard": "#BBDEFB"
}

fig_column.for_each_trace(
    lambda t: t.update(marker_color=color_map[t.name])
)
fig_column.update_layout(
    xaxis_title="Product Category",
    yaxis_title="Total Sales",
    template="plotly_white",
    yaxis_showgrid=True,
    legend_title="Type",
    title={
    "text": "Total Sales by Category",
    "x": 0.5,
    "y": 0.9,
    "xanchor": "center"
},

)
fig_column.update_xaxes(showline=True, linewidth=1, linecolor='black')
fig_column.update_yaxes(showline=True, linewidth=1, linecolor='black')

fig_column.update_yaxes(range=[0, 950000])

>### Insight
>>### Technology category has the highest total sales, followed by Furniture and Office Supplies.
-------------------

>## 2) Bar Chart — Total Profit by Region
>>## Audience Question:
>>>## Which region generates the top of total profit?

In [35]:
profit_by_region = df.groupby("region")["profit"].sum().reset_index()
profit_by_region = profit_by_region.sort_values("profit", ascending=False).reset_index(drop=True)

profit_by_region["type"] = "Standard"
profit_by_region.loc[0, "type"] = "Max"

fig_bar = px.bar(
    profit_by_region,
    x="profit",
    y="region",
    title="Total Profit by Region",
    color="type",
    text=profit_by_region["profit"] / 1000
)

fig_bar.update_yaxes(autorange="reversed")

fig_bar.update_traces(
    texttemplate="%{text:.0f}K",
    textposition="outside"
)

color_map = {
    "Max": "#1E88E5",
    "Standard": "#BBDEFB"
}

fig_bar.for_each_trace(
    lambda t: t.update(marker_color=color_map[t.name])
)

fig_bar.update_layout(
    xaxis_title="Total Profit",
    yaxis_title="Region",
    template="plotly_white",
    xaxis_showgrid=True,
    legend_title="Type",
    title={ "text": "Total Sales by Category",
    "x": 0.5,
    "y": 0.9,
    "xanchor": "center"}
)

fig_bar.update_xaxes(range=[0, 120000])
fig_bar.update_xaxes(showline=True, linewidth=2, linecolor='black')
fig_bar.update_yaxes(showline=True, linewidth=1, linecolor='black')
fig_bar.show()

>### Insight:
>>### The West region generates the highest total profit, followed by East, South, and Central.

---------------------

> # 3)Stacked Column Chart
>> ## How are sales distributed across segments within each category?

In [36]:
sales_cat_seg=df.groupby(["category","segment"])["sales"].sum().reset_index()
sales_cat_seg=sales_cat_seg.sort_values(by="sales",ascending=False)

total_sales = sales_cat_seg.groupby("category")["sales"].sum().reset_index()

fig_Stacked_Column=px.bar(sales_cat_seg,
           color="segment",
           x="category",
           y="sales",
           title="Sales by Category and segment",
           text=sales_cat_seg["sales"] / 1000,
            orientation="v",
            barmode  = 'stack'
        )

fig_Stacked_Column.update_traces(
    texttemplate='%{text:.0f}K',
    textposition="inside"

)

for i, row in total_sales.iterrows():
    fig_Stacked_Column.add_annotation(
        x=row["category"],
        y=row["sales"],
        text=f"Total: {row['sales']/1000:.0f}K",
        showarrow=False,
        yshift=12,
        font=dict(size=12, color="black")
    )


fig_Stacked_Column.update_layout(
    xaxis_title="Product Category",
    yaxis_title="Total sales", 
    xaxis_showgrid=True, 
    template="plotly_white",
    legend_title="Segment",
      title={ "text": "Sales by Category and segment",
    "x": 0.5,
    "y": 0.9,
    "xanchor": "center"}
)

fig_Stacked_Column.update_xaxes(showline=True, linewidth=1, linecolor='black')
fig_Stacked_Column.update_yaxes(showline=True, linewidth=1, linecolor='black')

fig_Stacked_Column.show()

>### Insight:
>>### Consumer segment contributes the largest share of sales across most categories, especially in Technology.
-------------------------------------

># 4) Stacked Bar Chart 
>>## How is profit distributed across segments within each region?

In [23]:

pro_reg_seg=df.groupby(["region","segment"])["profit"].sum().reset_index()
pro_reg_seg=pro_reg_seg.sort_values("profit",ascending=False)

Total_profit=pro_reg_seg.groupby("region").sum().reset_index()

fig_Stacked_Bar=px.bar(
    pro_reg_seg,
    x="profit",
    y="region",
    title="Profit by Region & Segment",
    color="segment",
    text=pro_reg_seg["profit"]/1000,
    orientation="h",
    barmode  = 'stack',
)

fig_Stacked_Bar.update_yaxes(autorange="reversed")


fig_Stacked_Bar.update_traces(
    texttemplate='%{text:.0f}K',
    textposition="inside"
)

for i, row in Total_profit.iterrows():
    fig_Stacked_Bar.add_annotation(
        x=row["profit"],
        y=row["region"],
        text=f"Total: {row['profit']/1000:.0f}K",
        showarrow=False,
        xshift=40,
        font=dict(size=12, color="black")
    )


fig_Stacked_Bar.update_layout(
    xaxis_title="Total profit",
    yaxis_title="Region",
    xaxis_showgrid=True,
    template="plotly_white",
    legend_title="segment",
    title={ "text": "Profit by Region & Segment",
    "x": 0.5,
    "y": 0.9,
    "xanchor": "center"}
    
)

fig_Stacked_Bar.update_xaxes(showline=True, linewidth=2, linecolor='black')
fig_Stacked_Bar.update_yaxes(showline=True, linewidth=1, linecolor='black')


fig_Stacked_Bar.show()

>### Insight:
>>### The Consumer segment contributes the largest share of profit across most regions, especially in the West region.
--------------------------

>## 5) Clustered Column Chart
>>### How do different customer segments compare within each category?

In [24]:
sale_cate_seg_col=df.groupby(["category","segment"])["sales"].sum().reset_index()
sale_cate_seg_col=sale_cate_seg_col.sort_values("sales",ascending=False)

fig_clus_clumon=px.bar(
    sale_cate_seg_col,
    x="category",
    y="sales",
    title="Sales by Category & Segment",
    color="segment",
    barmode="group", #*** 
    text=sale_cate_seg_col["sales"]/1000,
    orientation="v",
)

fig_clus_clumon.update_traces(
    texttemplate='%{text:.0f}K',
    textposition="outside"
    )
fig_clus_clumon.update_layout(
    xaxis_title="Product Category",
    yaxis_title="Total Sales",
    yaxis_showgrid=True,
    template="plotly_white",
    legend_title="segment",
    title={ "text": "Sales by Category & Segment",
    "x": 0.5,
    "y": 0.9,
    "xanchor": "center"}

)
fig_clus_clumon.update_xaxes(showline=True, linewidth=1, linecolor='black')
fig_clus_clumon.update_yaxes(showline=True, linewidth=1, linecolor='black')


fig_clus_clumon.show()


>## Insight:
>>### Consumer segment generally has higher sales across most categories compared to Corporate and Home Office.
--------------------------

>## 7) Clustered Bar Chart
>>### How do customer segments compare side-by-side within each region?

In [25]:
pro_reg_seg_bar=df.groupby(["region","segment"])["profit"].sum().reset_index()
pro_reg_seg_bar=pro_reg_seg_bar.sort_values("profit",ascending=False)

fig_clus_bar=px.bar(
    pro_reg_seg_bar,
    x="profit",
    y="region",
    title="Profit by Region & Segment",
    color="segment",
    text=pro_reg_seg_bar["profit"]/1000,
    barmode="group",
    orientation="h",
    )

fig_clus_bar.update_yaxes(autorange="reversed")


fig_clus_bar.update_traces(
    texttemplate='%{text:.0f}K',
    textposition="outside")

fig_clus_bar.update_layout(
    xaxis_title="Total Profit",
    yaxis_title="Region",
    xaxis_showgrid=True,
    template="plotly_white",
    legend_title="segment",
    title={ "text": "Profit by Region & Segment",
    "x": 0.5,
    "y": 0.9,
    "xanchor": "center"}

    )
fig_clus_bar.update_xaxes(showline=True, linewidth=1, linecolor='black')
fig_clus_bar.update_yaxes(showline=True, linewidth=1, linecolor='black')

fig_clus_bar.show()

>## Insight:
>>### Consumer segment generally has higher sales across most categories compared to Corporate and Home Office.
---------------

>## Relationship Charts(Scatter Chart ,Bubble Chart)

>## 8) Scatter Plot  — 2 Variables
>>### Is there a relationship between Sales and Profit?

In [26]:
df["outlier"] = (df["sales"] > 1000) & (df["profit"] < 0)
df["point_type"] = df["outlier"].apply(
    lambda x: "Outlier" if x else "Normal"
)

fig_scatter = px.scatter(
    df,
    x="sales",
    y="profit",
    title="Sales vs Profit (Outliers Highlighted)",
    color="point_type",
    hover_data=["category", "sub_category", "region", "segment"],
    opacity=0.6
)

color_map = {
    "Normal": "#90CAF9",
    "Outlier": "#A6EF46"  
}

fig_scatter.for_each_trace(
    lambda t: t.update(marker_color=color_map[t.name])
)
fig_scatter.update_traces(
    marker=dict(size=7, line=dict(width=1, color="black"))
)

fig_scatter.update_layout(
    xaxis_title="Sales (K)",
    yaxis_title="Profit (K)",
    template="plotly_white",
    xaxis_showgrid=True,
    yaxis_showgrid=True,
    legend_title="Point Type",
    title={ "text": "Scatter Chart Sales vs Profit with Quantity",
    "x": 0.5,
    "y": 0.9,
    "xanchor": "center"}
)

fig_scatter.update_xaxes(showline=True, linewidth=1, linecolor='black')
fig_scatter.update_yaxes(showline=True, linewidth=1, linecolor='black')


fig_scatter.show()

>## Insight:
>>### Several outliers show high sales but negative profit, indicating that heavy discounting or cost issues may lead to losses despite strong sales performance.
------------------

>## 9) Bubble Chart — 3 Variables
>>### How do Sales, Profit, and Quantity relate to each other?

In [27]:
df["outlier"] = (df["profit"] < 0) | (df["quantity"] > df["quantity"].quantile(0.95))
df["point_type"] = df["outlier"].apply(
    lambda x: "Outlier" if x else "Normal"
)

fig_Bubble=px.scatter(
    df,
    x="sales",
    y="profit",
    size="quantity",
    color="point_type",
    title="Bubble Chart Sales vs Profit with Quantity",
    hover_data=["category", "sub_category", "region", "segment"],
    opacity=0.35,
    size_max=40
    )

color_map = {
    "Normal": "#90CAF9",
    "Outlier": "#A6EF46"  
}

fig_Bubble.for_each_trace(
    lambda t: t.update(marker_color=color_map[t.name])
)

fig_Bubble.update_traces(
    marker=dict(
        sizemode="area",
        sizeref=2.*max(df["quantity"])/(40**2),
        line=dict(width=1, color="black")
    )
)

fig_Bubble.update_layout(
    xaxis_title="Sales (K)",
    yaxis_title="Profit (K)",
    template="plotly_white",
    xaxis_showgrid=True,
    yaxis_showgrid=True,
    legend_title="point_type",
    title={ "text": "Bubble Chart Sales vs Profit with Quantity",
    "x": 0.5,
    "y": 0.9,
    "xanchor": "center"}
)

fig_Bubble.add_scatter(
    x=[30000, 30000, 30000],
    y=[8000, 6000, 3500],
    mode="markers+text",
    marker=dict(
        size=[10, 25, 40],
        color="gray",
        opacity=0.5
    ),
    text=["Low", "Med", "High"],
    textposition="middle right",
)

fig_Bubble.update_xaxes(showline=True, linewidth=1, linecolor='black')
fig_Bubble.update_yaxes(showline=True, linewidth=1, linecolor='black')


fig_Bubble.show()


>## Insight:
>>### Larger bubbles indicate higher quantities, helping identify high-volume orders and their profitability.
-------------------

>## Distribution Charts (Histogram Chart,Box Chart ,Violin Chart )

>## 10) Histogram Chart
>>### How frequently are product quantities ordered?

In [28]:
fig_hist = px.histogram(
    df,
    x="quantity",
    nbins=15,
    title="Distribution of Profit",
    color_discrete_sequence=["#7F8D80"]
)

fig_hist.update_traces(
    texttemplate='%{y}',
    textposition='outside',
)

fig_hist.update_layout(
    xaxis_title="quantity",
    yaxis_title="Frequency",
    template="plotly_white",
    yaxis_showgrid=True,
    title={ "text": "Histogram  — quantity Distribution",
    "x": 0.5,
    "y": 0.9,
    "xanchor": "center"}
)



fig_hist.update_xaxes(showline=True, linewidth=1, linecolor='black')
fig_hist.update_yaxes(showline=True, linewidth=1, linecolor='black')





fig_hist.show()


>## Insight:
>>### Most orders contain small quantities, while large-quantity orders are rare.
>>### Right-skewed distribution

># 11) Box plot
>>## Are there outliers in profit values?

In [29]:
fig_Box = px.box(
    df,
    y="profit",
    title="Profit Distribution",
    color_discrete_sequence=["#3F51B5"]
    ,points='outliers',
    

)

fig_Box.update_traces(
    marker=dict(color="#E53935", size=6),
    line=dict(color="#90CAF9"))

fig_Box.add_scatter( ## legend
    mode="markers",
    marker=dict(color="#90CAF9", size=8), 
    name="Standard"
)

fig_Box.data[0].name = "Outliers"
fig_Box.data[0].showlegend = True

fig_Box.update_yaxes(range=[-500, 500])

fig_Box.update_layout(
    yaxis_title="Profit",
    template="plotly_white",
    yaxis_showgrid=True,
    xaxis_title="Profit",
    title={ "text": "Profit by Region & Segment",
    "x": 0.5,
    "y": 0.9,
    "xanchor": "center"}
)
median_profit = df["profit"].median()

fig_Box.add_annotation(
    x=0,
    y=median_profit,
    text=f"Median: {median_profit:.2f}",
    showarrow=True,
    arrowhead=2,
    ax=80,
    ay=0,
    bgcolor="white",
    bordercolor="black",
    font=dict(color="black")
)

fig_Box.update_xaxes(showline=True, linewidth=2, linecolor='black')
fig_Box.update_yaxes(showline=True, linewidth=2, linecolor='black')

q1 = df["profit"].quantile(0.25)
median = df["profit"].median()
q3 = df["profit"].quantile(0.75)
minimum = df["profit"].min()
maximum = df["profit"].max()

fig_Box.add_annotation(
    x=0.35,
    y=250,
    text=(
        f"Max: {maximum:.0f}<br>"
        f"Q3: {q3:.2f}<br>"
        f"Median: {median:.2f}<br>"
        f"Q1: {q1:.2f}<br>"
        f"Min: {minimum:.0f}"
    ),
    bgcolor="white",
    bordercolor="black",
    font=dict(size=11, color="black")
)


fig_Box.show()

>## Insight:
>>### Most profit values are concentrated around zero, indicating that the majority of transactions generate low margins. The highlighted outliers show extreme profit and loss cases, suggesting variability in pricing and discount strategies.

-------------------

># 12) Violin Plot
>>### How are profits distributed and where are the outliers?

In [30]:
fig_violin=px.violin(
    df,
    y="profit",
    box=True,
    title="Violin Plot — Profit Distribution",
    color_discrete_sequence=["#CAC1CE"]
)

fig_violin.update_layout(
    height=600,
    width=900,    
    yaxis_title="Profit",
    template="plotly_white",
    yaxis_showgrid=True,
    xaxis_title="Profit Distribution",
    title={ "text": "Violin Plot — Profit Distribution",
    "x": 0.5,
    "y": 0.9,
    "xanchor": "center"}
    
    )
fig_violin.update_yaxes(range=[-1000, 1000])

median_profit = df["profit"].median()

fig_violin.add_annotation(
    x=0,
    y=median_profit,
    text=f"Median: {median_profit:.2f}",
    showarrow=True,
    arrowhead=2,
    ax=80,
    ay=0,
    font=dict(size=12, color="black"),
    bgcolor="white",
    bordercolor="black"
)


fig_violin.update_xaxes(showline=True, linewidth=1, linecolor='black')
fig_violin.update_yaxes(showline=True, linewidth=1, linecolor='black')

fig_violin.show()

>## Insight:
>>### The violin plot shows a high concentration of profit values around zero, indicating that most transactions yield low profits. The thin tails on both ends highlight the presence of extreme outliers, representing significant gains and losses..
----------------

># Time-Series Charts (Line Chart , Area Chart  )
>>## 13) Line Chart
>>>### How do sales change over time?

In [31]:
sales_over_time=df.groupby("year_month")["sales"].sum().reset_index()

sales_over_time=sales_over_time.sort_values("year_month",ascending=True)




fig_line=px.line(
    sales_over_time,
    x="year_month",
    y="sales",
    title="Sales Trend Over Time",
    markers=True   #  يظهر نقط على الخط
    )

fig_line.update_layout(
    xaxis_title="Time",
    yaxis_title="Total Sales",
    xaxis_showgrid=True,
    yaxis_showgrid=True,
    template="plotly_white",
    title={ "text": "(Line Chart) Sales Over Time",
    "x": 0.5,
    "y": 0.9,
    "xanchor": "center"}
    )

fig_line.update_xaxes(showline=True, linewidth=1, linecolor='black')
fig_line.update_yaxes(showline=True, linewidth=1, linecolor='black')

fig_line.show()

>## Insight:
>>### Sales show an overall upward trend over time, with clear monthly fluctuations and strong peaks near the end of 2017.
--------------

In [32]:
sales_over_time=df.groupby("year_month")["sales"].sum().reset_index()

sales_over_time=sales_over_time.sort_values("year_month",ascending=True)


fig_area=px.area(
    sales_over_time,
    x="year_month",
    y="sales",
    title="(Area Chart) profit Over Time "
    )

fig_area.update_layout(
    xaxis_title="Time",
    yaxis_title="Total sales",
    template="plotly_white",
    xaxis_showgrid=True,
    yaxis_showgrid=True,
    title={ "text": "(Area Chart) profit Over Time",
    "x": 0.5,
    "y": 0.9,
    "xanchor": "center"}
)


fig_area.update_xaxes(showline=True, linewidth=1, linecolor='black')
fig_area.update_yaxes(showline=True, linewidth=1, linecolor='black')

fig_area.show()

># 14) Area Chart
>> # What is the trend of total profit over time?

In [33]:
profit_over_time=df.groupby("year_month")["profit"].sum().reset_index()

profit_over_time=profit_over_time.sort_values("year_month",ascending=True)


fig_area=px.area(
    profit_over_time,
    x="year_month",
    y="profit",
    title="(Area Chart) profit Over Time "
    )

fig_area.update_layout(
    xaxis_title="Time",
    yaxis_title="Total profit",
    template="plotly_white",
    xaxis_showgrid=True,
    yaxis_showgrid=True,
    title={ "text": "(Area Chart) profit Over Time",
    "x": 0.5,
    "y": 0.9,
    "xanchor": "center"}
)


fig_area.update_xaxes(showline=True, linewidth=1, linecolor='black')
fig_area.update_yaxes(showline=True, linewidth=1, linecolor='black')

fig_area.show()

># Insight:
>>#### Total profit generally increases over time, although there are some fluctuations between months. The highest profits appear toward the end of the timeline